### PR TITLE
Fix Example

### PR DESCRIPTION
**Pull request by hst-m**
***
<a href="https://pr-preview.s3.amazonaws.com/hst-m/webtransport/pull/262.html" title="Last updated on May 17, 2021, 11:31 AM UTC (4930bfd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/262/76d2423...hst-m:4930bfd.html" title="Last updated on May 17, 2021, 11:31 AM UTC (4930bfd)">Diff</a>

### CODE REVIEW

**Comment by yutakahirano** [comment]
I think the current example is correct: please see https://streams.spec.whatwg.org/#rs-asynciterator.

**Comment by hst-m** [comment]
@yutakahirano you are right, but does this other example need to be fixed? I updated PR

**Review by ricea — COMMENTED** [review]
This looks correct to me.

**Review by yutakahirano — APPROVED** [review]
Thank you, LGTM.

**Comment by yutakahirano** [comment]
You need to do something about patent policy, but I don't know what to do. @wilaw , do you know?

**Comment by wilaw** [comment]
@hst-m thanks for your contribution. It failed an ipr check since your github account is not linked to your W3C account. Please link the two at https://www.w3.org/users/myprofile/connectedaccounts to avoid delays in processing future PRs. We went ahead and marked this PR as "acceptable as non-substantitve" since its an example fix, to avoid any delay in merging.

**Review by jan-ivar — APPROVED** [review]

**Pull request merged**
